name = "fediverse-alias"
compatibility_date = "2023-01-01"

routes = [
  { pattern = "tedps.tk/.well-known/*", zone_name = "tedps.tk" },
  { pattern = "tedsmc.tk/.well-known/*", zone_name = "tedsmc.tk" }
]

# [vars]
# MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "dns"
database_id = "9e272ec1-97d4-4d4a-ace6-cc081f662ead"
